apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka
  namespace: flux-system
spec:
  releaseName: kafka
  chart:
    spec:
      chart: ./
      sourceRef:
        kind: GitRepository
        name: benua-kafka
  install:
    createNamespace: true
  targetNamespace: kafka
  interval: 1m0s
