apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kps
  namespace: flux-system
spec:
  releaseName: kps
  chart:
    spec:
      chart: ./
      sourceRef:
        kind: GitRepository
        name: benua-kps
  install:
    createNamespace: true
  targetNamespace: monitoring
  interval: 1m0s
