apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 1m0s
  timeout: 1m0s
  url: https://kubernetes.github.io/ingress-nginx


---

apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      version: "*"
  install:
    createNamespace: true
  targetNamespace: ingress-nginx
  interval: 1m0s

### https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx

  values:
    controller:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true 
      hostPort:
        enable: true
      kind: DaemonSet
      service:
        type: ClusterIP
      publishService:
        enabled: false
      extraArgs: 
        publish-status-address: 62.217.178.210

      config:
#        http-snippet: "proxy_cache_path /tmp/nginx_cache levels=1:2 keys_zone=mycache:32m use_temp_path=off max_size=4g inactive=24h;"
         enable-opentracing: "true"
#        jaeger-collector-host: "10.43.245.201"
#        jaeger-collector-port: "14268"
         jaeger-endpoint: "http://signoz-otel-collector.signoz.svc.cluster.local:14268/api/traces"
